#!/usr/bin/env bash
# Shared mock agent implementation for the `claude` and `copilot` fakes.
#
# It stands in for the real agent CLI: no LLM, no network. It records how it was
# invoked (to $MOCK_AGENT_LOG) and simulates the skill's side effects so the
# harness around it can be tested deterministically.
#
# Mode is taken from the environment run-agent.sh exports (unambiguous — the update
# prompt itself mentions "appmap-review" as the downstream step, so prompt text can't
# decide the mode):
#   - REPORT_FILE set      -> review mode  (writes $REPORT_FILE)
#   - GOLD_TRACES_DIR set  -> update mode  (creates gold traces)
# Test knobs:
#   MOCK_NO_REPORT=1   review mode writes nothing (to test the missing-report error)
set -euo pipefail

# Capture the prompt (the value after -p/--prompt) and log the full invocation.
prompt=""
args=("$@")
while [[ $# -gt 0 ]]; do
  case "$1" in
    -p|--prompt) prompt="${2:-}"; shift 2 ;;
    *) shift ;;
  esac
done

if [[ -n "${MOCK_AGENT_LOG:-}" ]]; then
  { printf 'agent=%s\n' "$(basename "$0")"
    printf 'args=%s\n' "${args[*]}"
    printf 'prompt<<END\n%s\nEND\n' "$prompt"
  } >> "$MOCK_AGENT_LOG"
fi

if [[ -n "${REPORT_FILE:-}" ]]; then
  # Review mode.
  if [[ "${MOCK_NO_REPORT:-}" == "1" ]]; then
    echo "mock agent: intentionally not writing a report"
    exit 0
  fi
  : "${REPORT_FILE:?mock agent (review) needs REPORT_FILE}"
  mkdir -p "$(dirname "$REPORT_FILE")"
  cat > "$REPORT_FILE" <<EOF
# AppMap Behavioral Review — mock

**Revisions:** \`${HEAD_REVISION:-head}\` vs \`${BASE_REVISION:-base}\`

Mock review generated by the test harness.
EOF
  echo "mock agent: wrote review to $REPORT_FILE"
else
  # Update (gold-traces) mode.
  : "${GOLD_TRACES_DIR:?mock agent (update) needs GOLD_TRACES_DIR}"
  mkdir -p "$GOLD_TRACES_DIR/baseline/appmaps"
  cat > "$GOLD_TRACES_DIR/appmap_golden_set.yaml" <<'EOF'
schema_version: 1
commands:
  record: "npx appmap-node npx jest {test_file} -t {test_name}"
entries:
  - feature: mock
    test_file: test/index.test.js
    test_name: adds numbers
    appmap_path: jest/adds_numbers.appmap.json
    summary: Mock gold trace produced by the test harness.
EOF
  echo '{"version":"mock"}' > "$GOLD_TRACES_DIR/baseline/appmaps/mock.appmap.json"
  echo "mock agent: seeded $GOLD_TRACES_DIR"
fi
